x-logging: &default-logging
    options: { max-size: '10m', max-file: '3' }

x-mongo-common: &mongo-common
    image: ${MONGO_IMAGE}
    profiles: ['infra']
    logging: *default-logging
    environment:
        MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
        MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
    command: mongod --replSet ${MONGO_REPLICA} --keyFile /etc/mongodb/mongodb.key --bind_ip_all
    volumes: ['mongodb_key:/etc/mongodb']
    networks: ['default']
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    restart: always
    depends_on: ['mongo-key-generator']
    healthcheck:
        test: "mongosh --quiet -u $MONGO_USERNAME -p $MONGO_PASSWORD --authenticationDatabase admin --eval 'rs.isMaster().ismaster || rs.isMaster().secondary'"
        interval: 5s
        timeout: 5s

x-redis-common: &redis-common
    image: ${REDIS_IMAGE}
    command: 'redis-server --port 6379 --requirepass $REDIS_PASSWORD --masterauth $REDIS_PASSWORD --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes'
    profiles: ['infra']
    logging: *default-logging
    networks: ['default']
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    restart: always
    healthcheck:
        test: 'redis-cli -a $REDIS_PASSWORD ping'
        interval: 5s
        timeout: 5s

x-nats-common: &nats-common
    image: ${NATS_IMAGE}
    profiles: ['infra']
    logging: *default-logging
    networks: ['default']
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    restart: always
    healthcheck:
        test: wget -qO- http://localhost:8222/varz || exit 1
        interval: 5s
        timeout: 5s

x-app-common: &app-common
    profiles: ['apps']
    logging: *default-logging
    environment: ['NODE_ENV=production']
    env_file: .env.test
    networks: ['default']
    extra_hosts:
        - 'host.docker.internal:host-gateway'

services:
    redis1:
        <<: *redis-common
        container_name: redis1
        ports:
            - '6379:6379'
    redis2:
        <<: *redis-common
        container_name: redis2
        ports:
            - '6380:6379'
    redis3:
        <<: *redis-common
        container_name: redis3
        ports:
            - '6381:6379'
    redis4:
        <<: *redis-common
        container_name: redis4
        ports:
            - '6382:6379'
    redis5:
        <<: *redis-common
        container_name: redis5
        ports:
            - '6383:6379'
    redis6:
        <<: *redis-common
        container_name: redis6
        ports:
            - '6384:6379'
    redis-setup:
        image: ${REDIS_IMAGE}
        container_name: redis-setup
        profiles: ['infra']
        depends_on:
            redis1: { condition: service_healthy }
            redis2: { condition: service_healthy }
            redis3: { condition: service_healthy }
            redis4: { condition: service_healthy }
            redis5: { condition: service_healthy }
            redis6: { condition: service_healthy }
        command: >-
            sh -c "
            REDIS_LIST=\"redis1:6379 redis2:6379 redis3:6379 redis4:6379 redis5:6379 redis6:6379 \"

            echo 'yes' | redis-cli -a $REDIS_PASSWORD --cluster create $${REDIS_LIST} --cluster-replicas 1
            "
        networks: ['default']
        extra_hosts:
            - 'host.docker.internal:host-gateway'
            # REDIS_LIST=\"host.docker.internal:6379 host.docker.internal:6380 host.docker.internal:6381 host.docker.internal:6382 host.docker.internal:6383 host.docker.internal:6384\"

    mongo-key-generator:
        image: ${MONGO_IMAGE}
        container_name: mongo-key-generator
        profiles: ['infra']
        command: 'sh -c "openssl rand -base64 768 > mongodb.key && chmod 400 mongodb.key && chown mongodb:mongodb mongodb.key"'
        volumes: ['mongodb_key:/mongodb_key']
        working_dir: /mongodb_key
    mongo1:
        <<: *mongo-common
        container_name: mongo1
        ports:
            - '27017:27017'
    mongo2:
        <<: *mongo-common
        container_name: mongo2
        ports:
            - '27018:27017'
    mongo3:
        <<: *mongo-common
        container_name: mongo3
        ports:
            - '27019:27017'
    mongo-setup:
        image: ${MONGO_IMAGE}
        container_name: mongo-setup
        profiles: ['infra']
        depends_on:
            mongo1: { condition: service_healthy }
            mongo2: { condition: service_healthy }
            mongo3: { condition: service_healthy }
        networks: ['default']
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        command: >
            sh -c "
            MONGO_HOST1_URI=\"mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo1:27017/?authSource=admin\"

            mongosh $${MONGO_HOST1_URI} --eval \"
                rs.initiate({
                    _id: \\\"${MONGO_REPLICA}\\\",
                    members: [
                      {_id: 0, host: \\\"host.docker.internal:27017\\\"},
                      {_id: 1, host: \\\"host.docker.internal:27018\\\"},
                      {_id: 2, host: \\\"host.docker.internal:27019\\\"}
                    ]
                })
            \"

            MONGO_HOSTS=\"mongo1:27017,mongo2:27017,mongo3:27017\";
            MONGO_URI=\"mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@$${MONGO_HOSTS}/?authSource=admin&replicaSet=${MONGO_REPLICA}\";

            mongosh $${MONGO_URI} --eval \"db.test.insertOne({test: 'test'})\"
            "

    nats1:
        <<: *nats-common
        container_name: nats1
        command: '--cluster_name ${NATS_CLUSTER} --cluster nats://0.0.0.0:6222 --http_port 8222'
        ports:
            - '4222:4222'

    nats2:
        <<: *nats-common
        container_name: nats2
        command: '--cluster_name ${NATS_CLUSTER} --cluster nats://0.0.0.0:6222 --http_port 8222 --routes=nats://nats1:6222'
        ports:
            - '4223:4222'
        depends_on: ['nats1']

    nats3:
        <<: *nats-common
        container_name: nats3
        command: '--cluster_name ${NATS_CLUSTER} --cluster nats://0.0.0.0:6222 --http_port 8222 --routes=nats://nats1:6222'
        ports:
            - '4224:4222'
        depends_on: ['nats1']
    nats-setup:
        image: natsio/nats-box
        container_name: nats-setup
        profiles: ['infra']
        depends_on:
            nats1: { condition: service_healthy }
            nats2: { condition: service_healthy }
            nats3: { condition: service_healthy }
        networks: ['default']
        command: >
            sh -c "
            set -e;
            nats sub -s nats://nats1:4222 hello &
            nats pub -s "nats://nats2:4222" hello first;
            nats pub -s "nats://nats3:4222" hello second;
            "

    gateway:
        <<: *app-common
        build: { context: ., args: { APP_IMAGE: $APP_IMAGE, TARGET_APP: gateway } }
        image: ${SERVICE_GATEWAY_HOST}
        container_name: ${SERVICE_GATEWAY_HOST}
        ports:
            - '${SERVICE_GATEWAY_HTTP_PORT}:${SERVICE_GATEWAY_HTTP_PORT}'
        healthcheck:
            test: 'curl -f http://localhost:${SERVICE_GATEWAY_HTTP_PORT}/health'
            interval: 5s
            timeout: 5s
        volumes:
            - ./_output/logs/gateway:/app/_output/logs
            - ./_output/uploads:/app/_output/uploads

    applications:
        <<: *app-common
        build: { context: ., args: { APP_IMAGE: $APP_IMAGE, TARGET_APP: applications } }
        image: ${SERVICE_APPLICATIONS_HOST}
        container_name: ${SERVICE_APPLICATIONS_HOST}
        healthcheck:
            test: 'curl -f http://localhost:${SERVICE_APPLICATIONS_HTTP_PORT}/health'
            interval: 5s
            timeout: 5s
        volumes: ['./_output/logs/applications:/app/_output/logs']

    cores:
        <<: *app-common
        build: { context: ., args: { APP_IMAGE: $APP_IMAGE, TARGET_APP: cores } }
        image: ${SERVICE_CORES_HOST}
        container_name: ${SERVICE_CORES_HOST}
        healthcheck:
            test: 'curl -f http://localhost:${SERVICE_CORES_HTTP_PORT}/health'
            interval: 5s
            timeout: 5s
        volumes: ['./_output/logs/cores:/app/_output/logs']

    infrastructures:
        <<: *app-common
        build: { context: ., args: { APP_IMAGE: $APP_IMAGE, TARGET_APP: infrastructures } }
        image: ${SERVICE_INFRASTRUCTURES_HOST}
        container_name: ${SERVICE_INFRASTRUCTURES_HOST}
        healthcheck:
            test: 'curl -f http://localhost:${SERVICE_INFRASTRUCTURES_HTTP_PORT}/health'
            interval: 5s
            timeout: 5s
        volumes:
            - './_output/logs/infrastructures:/app/_output/logs'
            - './_output/uploads:/app/_output/uploads'

    apps-setup:
        image: ${APP_IMAGE}
        container_name: apps-setup
        profiles: ['apps']
        depends_on:
            gateway: { condition: service_healthy }
            applications: { condition: service_healthy }
            cores: { condition: service_healthy }
            infrastructures: { condition: service_healthy }

networks:
    default:

volumes:
    mongodb_key: {}
