x-common-base: &common-base
    logging:
        options: { max-size: '10m', max-file: '3' }
    networks: ['default']
    extra_hosts: ['host.docker.internal:host-gateway']

x-mongo-base: &mongo-base
    <<: *common-base
    image: ${MONGO_IMAGE}
    profiles: ['infra']
    environment:
        MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
        MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
    command: mongod --replSet ${MONGO_REPLICA} --keyFile /etc/mongodb/mongodb.key --bind_ip_all
    volumes: ['mongodb_key:/etc/mongodb']
    restart: always
    depends_on: ['mongo-key-generator']
    healthcheck:
        test: "mongosh --quiet -u $MONGO_USERNAME -p $MONGO_PASSWORD --authenticationDatabase admin --eval 'db.hello().isWritablePrimary || db.hello().secondary'"
        interval: 5s
        timeout: 5s

x-redis-base: &redis-base
    <<: *common-base
    image: ${REDIS_IMAGE}
    profiles: ['infra']
    restart: always
    healthcheck:
        test: ['CMD-SHELL', 'redis-cli -a $REDIS_PASSWORD ping']
        interval: 5s
        timeout: 5s
    command: >
        sh -euc 'redis-server --port 6379 \
          --cluster-enabled yes \
          --cluster-config-file nodes.conf \
          --cluster-announce-ip host.docker.internal \
          --cluster-announce-port $$ANNOUNCE_PORT \
          --cluster-announce-bus-port $$ANNOUNCE_BUS_PORT \
          --protected-mode no \
          --appendonly yes \
          --requirepass $REDIS_PASSWORD \
          --masterauth $REDIS_PASSWORD
        '

x-nats-base: &nats-base
    <<: *common-base
    image: ${NATS_IMAGE}
    profiles: ['infra']
    restart: always
    healthcheck:
        test: wget -qO- http://localhost:8222/varz || exit 1
        interval: 5s
        timeout: 5s

x-app-base: &app-base
    <<: *common-base
    profiles: ['apps']
    environment: ['NODE_ENV=production']
    healthcheck:
        test: 'curl -f http://localhost:$HTTP_PORT/health'
        interval: 5s
        timeout: 5s
    env_file: .env.test

services:
    redis1:
        <<: *redis-base
        container_name: redis1
        environment:
            ANNOUNCE_PORT: $REDIS_PORT1
            ANNOUNCE_BUS_PORT: 1$REDIS_PORT1
        ports: ['$REDIS_PORT1:6379', '1$REDIS_PORT1:16379']

    redis2:
        <<: *redis-base
        container_name: redis2
        environment:
            ANNOUNCE_PORT: $REDIS_PORT2
            ANNOUNCE_BUS_PORT: 1$REDIS_PORT2
        ports: ['$REDIS_PORT2:6379', '1$REDIS_PORT2:16379']

    redis3:
        <<: *redis-base
        container_name: redis3
        environment:
            ANNOUNCE_PORT: $REDIS_PORT3
            ANNOUNCE_BUS_PORT: 1$REDIS_PORT3
        ports: ['$REDIS_PORT3:6379', '1$REDIS_PORT3:16379']

    redis4:
        <<: *redis-base
        container_name: redis4
        environment:
            ANNOUNCE_PORT: $REDIS_PORT4
            ANNOUNCE_BUS_PORT: 1$REDIS_PORT4
        ports: ['$REDIS_PORT4:6379', '1$REDIS_PORT4:16379']

    redis5:
        <<: *redis-base
        container_name: redis5
        environment:
            ANNOUNCE_PORT: $REDIS_PORT5
            ANNOUNCE_BUS_PORT: 1$REDIS_PORT5
        ports: ['$REDIS_PORT5:6379', '1$REDIS_PORT5:16379']

    redis6:
        <<: *redis-base
        container_name: redis6
        environment:
            ANNOUNCE_PORT: $REDIS_PORT6
            ANNOUNCE_BUS_PORT: 1$REDIS_PORT6
        ports: ['$REDIS_PORT6:6379', '1$REDIS_PORT6:16379']

    redis-setup:
        <<: *common-base
        image: ${REDIS_IMAGE}
        container_name: redis-setup
        profiles: ['infra']
        depends_on:
            redis1: { condition: service_healthy }
            redis2: { condition: service_healthy }
            redis3: { condition: service_healthy }
            redis4: { condition: service_healthy }
            redis5: { condition: service_healthy }
            redis6: { condition: service_healthy }
        command: >-
            sh -euc '
            REDIS_LIST="
                host.docker.internal:$REDIS_PORT1 \
                host.docker.internal:$REDIS_PORT2 \
                host.docker.internal:$REDIS_PORT3 \
                host.docker.internal:$REDIS_PORT4 \
                host.docker.internal:$REDIS_PORT5 \
                host.docker.internal:$REDIS_PORT6 \
                "

            echo "yes" | redis-cli -a ${REDIS_PASSWORD} --cluster create $${REDIS_LIST} --cluster-replicas 1
            '

    mongo-key-generator:
        image: ${MONGO_IMAGE}
        container_name: mongo-key-generator
        profiles: ['infra']
        command: >-
            sh -euc 'openssl rand -base64 768 > mongodb.key && chmod 400 mongodb.key && chown mongodb:mongodb mongodb.key'
        volumes: ['mongodb_key:/mongodb_key']
        working_dir: /mongodb_key

    mongo1:
        <<: *mongo-base
        container_name: mongo1
        ports: ['$MONGO_PORT1:27017']

    mongo2:
        <<: *mongo-base
        container_name: mongo2
        ports: ['$MONGO_PORT2:27017']

    mongo3:
        <<: *mongo-base
        container_name: mongo3
        ports: ['$MONGO_PORT3:27017']

    mongo-setup:
        <<: *common-base
        image: ${MONGO_IMAGE}
        container_name: mongo-setup
        profiles: ['infra']
        depends_on:
            mongo1: { condition: service_healthy }
            mongo2: { condition: service_healthy }
            mongo3: { condition: service_healthy }
        command: >
            sh -euc '
            MONGO_HOST1_URI="mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo1:27017/?authSource=admin"

            mongosh "$$MONGO_HOST1_URI" --eval "
                rs.initiate({
                _id: \"${MONGO_REPLICA}\",
                members: [
                    { _id: 0, host: \"host.docker.internal:${MONGO_PORT1}\" },
                    { _id: 1, host: \"host.docker.internal:${MONGO_PORT2}\" },
                    { _id: 2, host: \"host.docker.internal:${MONGO_PORT3}\" }
                    ]
                })
            "

            MONGO_HOSTS="mongo1:27017,mongo2:27017,mongo3:27017"
            MONGO_URI="mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@$${MONGO_HOSTS}/?authSource=admin&replicaSet=${MONGO_REPLICA}"

            mongosh "$$MONGO_URI" --eval "db.test.insertOne({ test: \"test\" })"
            '

    nats1:
        <<: *nats-base
        container_name: nats1
        command: '--cluster_name ${NATS_CLUSTER} --cluster nats://0.0.0.0:6222 --http_port 8222'
        ports: ['$NATS_PORT1:4222']

    nats2:
        <<: *nats-base
        container_name: nats2
        command: '--cluster_name ${NATS_CLUSTER} --cluster nats://0.0.0.0:6222 --http_port 8222 --routes=nats://nats1:6222'
        ports: ['$NATS_PORT2:4222']
        depends_on: ['nats1']

    nats3:
        <<: *nats-base
        container_name: nats3
        command: '--cluster_name ${NATS_CLUSTER} --cluster nats://0.0.0.0:6222 --http_port 8222 --routes=nats://nats1:6222'
        ports: ['$NATS_PORT3:4222']
        depends_on: ['nats1']

    nats-setup:
        <<: *common-base
        image: natsio/nats-box
        container_name: nats-setup
        profiles: ['infra']
        depends_on:
            nats1: { condition: service_healthy }
            nats2: { condition: service_healthy }
            nats3: { condition: service_healthy }
        command: >
            sh -euc '
            nats sub -s nats://nats1:4222 --count=2 hello >/tmp/sub.log 2>&1 &
            SUB_PID=$!

            sleep 0.3;
            nats pub -s nats://nats2:4222 hello first;
            nats pub -s nats://nats3:4222 hello second;
            wait $$SUB_PID;
            cat /tmp/sub.log;
            '

    gateway:
        <<: *app-base
        build: { context: ., args: { APP_IMAGE: $APP_IMAGE, TARGET_APP: gateway } }
        image: gateway
        container_name: gateway
        ports: ['${HTTP_PORT}:${HTTP_PORT}']
        volumes: [./_output/logs/gateway:/app/_output/logs, ./_output/uploads:/app/_output/uploads]

    applications:
        <<: *app-base
        build: { context: ., args: { APP_IMAGE: $APP_IMAGE, TARGET_APP: applications } }
        image: applications
        container_name: applications
        volumes: ['./_output/logs/applications:/app/_output/logs']

    cores:
        <<: *app-base
        build: { context: ., args: { APP_IMAGE: $APP_IMAGE, TARGET_APP: cores } }
        image: cores
        container_name: cores
        volumes: ['./_output/logs/cores:/app/_output/logs']

    infrastructures:
        <<: *app-base
        build: { context: ., args: { APP_IMAGE: $APP_IMAGE, TARGET_APP: infrastructures } }
        image: infrastructures
        container_name: infrastructures
        volumes:
            [
                './_output/logs/infrastructures:/app/_output/logs',
                './_output/uploads:/app/_output/uploads'
            ]

    apps-setup:
        image: ${APP_IMAGE}
        container_name: apps-setup
        profiles: ['apps']
        depends_on:
            gateway: { condition: service_healthy }
            applications: { condition: service_healthy }
            cores: { condition: service_healthy }
            infrastructures: { condition: service_healthy }

networks:
    default:

volumes:
    mongodb_key: {}
