packages:
    - 'apps/*'
    - 'libs/*'
    - 'infra/tests'
    - 'tests/*'
    - 'tools/*'

saveExact: true

allowBuilds:
    'bcrypt@6.0.0': true
    cpu-features: false
    'fsevents@2.3.2': true
    'fsevents@2.3.3': true
    protobufjs: false
    ssh2: false
    'unrs-resolver@1.12.2': true
