x-mongo-base: &mongo-base
    extends: { file: ./compose.common.yml, service: common-options }
    image: $MONGO_IMAGE
    deploy: { resources: { limits: { memory: 1g } } }
    environment:
        { MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME, MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD }
    # Prevents "Too many open files" errors
    ulimits: { nofile: { soft: 65536, hard: 65536 } }
    command: >
        mongod --replSet $MONGO_REPLICA_SET
        --keyFile /etc/mongodb/mongodb.key
        --bind_ip_all
        --wiredTigerCacheSizeGB 0.25
    volumes: ['mongodb_key:/etc/mongodb']
    depends_on: ['mongo-key-generator']

services:
    mongo-key-generator:
        container_name: mongo-key-generator
        image: $MONGO_IMAGE
        command: |
            sh -euc '
            openssl rand -base64 768 > mongodb.key &&
            chmod 400 mongodb.key &&
            chown mongodb:mongodb mongodb.key
            '
        volumes: ['mongodb_key:/mongodb_key']
        working_dir: /mongodb_key

    mongo1:
        <<: *mongo-base
        container_name: mongo1
        ports: ['$MONGO_PORT1:27017']
        healthcheck:
            test: >
                mongosh  "mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@$MONGO_HOST1:$MONGO_PORT1/?authSource=admin"
                --eval "db.adminCommand('ping')"

    mongo2:
        <<: *mongo-base
        container_name: mongo2
        ports: ['$MONGO_PORT2:27017']
        healthcheck:
            test: >
                mongosh  "mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@$MONGO_HOST2:$MONGO_PORT2/?authSource=admin"
                --eval "db.adminCommand('ping')"

    mongo3:
        <<: *mongo-base
        container_name: mongo3
        ports: ['$MONGO_PORT3:27017']
        healthcheck:
            test: >
                mongosh  "mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@$MONGO_HOST3:$MONGO_PORT3/?authSource=admin"
                --eval "db.adminCommand('ping')"

    mongo-setup:
        extends: { file: ./compose.common.yml, service: common-options }
        container_name: mongo-setup
        image: $MONGO_IMAGE
        depends_on:
            {
                mongo1: { condition: service_healthy },
                mongo2: { condition: service_healthy },
                mongo3: { condition: service_healthy }
            }
        command: |
            sh -eucx '
            mongosh  "mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@$MONGO_HOST1:$MONGO_PORT1/?authSource=admin" \
                --eval "
                    rs.initiate({
                    _id: \"$MONGO_REPLICA_SET\",
                    members: [
                        { _id: 0, host: \"$MONGO_HOST1:$MONGO_PORT1\" },
                        { _id: 1, host: \"$MONGO_HOST2:$MONGO_PORT2\" },
                        { _id: 2, host: \"$MONGO_HOST3:$MONGO_PORT3\" }
                        ]
                    })
                    "
            '
    mongo-gui:
        extends: { file: ./compose.common.yml, service: common-options }
        container_name: mongo-gui
        image: mongo-express:latest
        restart: always
        depends_on: { mongo-setup: { condition: service_completed_successfully } }
        environment:
            {
                ME_CONFIG_BASICAUTH: 'false',
                ME_CONFIG_MONGODB_URL: 'mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@mongo1:27017,mongo2:27017,mongo3:27017/?authSource=admin&replicaSet=$MONGO_REPLICA_SET'
            }
        ports: ['8081:8081']

volumes:
    mongodb_key: {}
