services:
    minio:
        extends: { file: ./compose.common.yml, service: common-options }
        container_name: minio
        image: ${MINIO_IMAGE}
        deploy: { resources: { limits: { memory: 512m } } }
        shm_size: '8m'
        ports: ['9000:9000', '9001:9001']
        environment:
            MINIO_ROOT_USER: ${S3_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
            MINIO_BROWSER_REDIRECT_URL: ${S3_ENDPOINT}
        command: 'server /data --console-address :9001'
        healthcheck:
            test: 'curl -fsS http://localhost:9000/minio/health/ready'

    minio-setup:
        container_name: minio-setup
        image: amazon/aws-cli:latest
        depends_on:
            minio:
                condition: service_healthy
        entrypoint: /bin/sh
        command: >
            -c "
            aws --endpoint-url http://minio:9000 s3 mb s3://${S3_BUCKET} ||
            aws --endpoint-url http://minio:9000 s3 ls s3://${S3_BUCKET}
            "
        environment:
            AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY}
            AWS_SECRET_ACCESS_KEY: ${S3_SECRET_KEY}
            AWS_DEFAULT_REGION: ${S3_REGION}
            AWS_EC2_METADATA_DISABLED: 'true'
            S3_BUCKET: ${S3_BUCKET}
