global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
    - job_name: 'nats'
      metrics_path: /metrics
      static_configs:
          - targets: ['nats-exporter1:7777']
            labels: { instance: 'nats1' }
          - targets: ['nats-exporter2:7777']
            labels: { instance: 'nats2' }
          - targets: ['nats-exporter3:7777']
            labels: { instance: 'nats3' }

    - job_name: 'prometheus'
      static_configs:
          - targets: ['prometheus:9090']
