x-app-base: &app-base
    environment: ['NODE_ENV=production']
    env_file: .env
    logging: { options: { max-size: '1m', max-file: '1' } }
    extra_hosts: ['host.docker.internal:host-gateway']
    healthcheck:
        {
            retries: 5,
            start_period: 10s,
            interval: 3s,
            timeout: 3s,
            test: 'curl -fsS http://localhost:$HTTP_PORT/health'
        }

services:
    app:
        <<: *app-base
        build: { context: . }
        image: nest-mono
        container_name: app
        ports: ['${HTTP_PORT}:${HTTP_PORT}']

    apps-setup:
        image: docker:cli
        container_name: apps-setup
        depends_on:
            app: { condition: service_healthy }
