name: Publish
on:
    push:
        branches: ['main']

permissions:
    contents: write
    pull-requests: write
    id-token: write

concurrency:
    group: publish-${{ github.ref }}
    cancel-in-progress: false

jobs:
    publish:
        runs-on: ubuntu-24.04-arm
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@v5

            - uses: actions/setup-node@v4
              with:
                  node-version: 24
                  registry-url: 'https://registry.npmjs.org'

            - run: npm install

            - name: Create Release Pull Request or Publish
              uses: changesets/action@v1
              with:
                  publish: npm run changeset:publish
                  title: 'chore: version packages'
                  commit: 'chore: version packages'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_CONFIG_PROVENANCE: true
